### ISSUE TITLE
Links are broken

### ISSUE THREAD

**Issue by 0x8BADFOOD** [igor-baiborodine/kiroule.com#95]
Hey Igor,

Links on your blog are broken. Please check and fix:

https://www.kiroule.com/article/building-your-blog-the-geeky-way/

Thanks

**Comment by igor-baiborodine** [comment]
Hi,

I checked them and all four of them work fine.

Thanks,

Igor

**Comment by 0x8BADFOOD** [comment]
It was my internal issue with redirections.
Thanks for quick reply.
